### ISSUE TITLE
Query Uniswap markets/exchanges

### ISSUE THREAD

**Issue by sbrichards** [Uniswap/uniswap-sdk#2]
Is there any way to query the existing markets on Uniswap (i.e. ETH <> ERC20 exchanges)? 

It looks like the Uniswap frontend just [maintains a hardcoded list](https://github.com/Uniswap/uniswap-frontend/blob/beta/src/contexts/Tokens.js#L30)?

I took a look at the contracts and the only public method I see is the `getExchange` on uniswap_factory.vy... I suppose that could be used to query if a given token exchange exists? Any other way to source a list of markets that I'm missing? Thanks!

**Comment by NoahZinsmeister** [comment]
Hi @sbrichards! Yes there is, one way to do it is call `tokenCount()` on the factory, then call `getTokenWithId(<id>)` with each id from 1 to `tokenCount()` to get token addresses. You could then call `getExchange(<tokenAddress>)`
