### ISSUE TITLE
Providing your own infura api key to the SDK.

### ISSUE THREAD

**Issue by poptardd** [Uniswap/uniswap-sdk#37]
Calls to the network with SDK bring up rate limits pretty easily while developing. Is it possible to provide your own infura API key? Looked through the docs and there is no answer regarding that.

**Comment by thanhnguyennguyen** [comment]
Always get this error 
![image](https://user-images.githubusercontent.com/17243442/93344346-c3dd6400-f85b-11ea-9d6b-1c10ff92b551.png)
Please allow us specify our own api key

**Comment by poptardd** [comment]
You can actually provide your own provider for the fetch functions. Check the docs. 

`fetchPairData` has it as third argument.
