### ISSUE TITLE
"use pairAddress to fetch reserves here"

### ISSUE THREAD

**Issue by i-schuetz** [Uniswap/uniswap-sdk#45]
I was looking at the [docs](https://uniswap.org/docs/v2/javascript-SDK/fetching-data/)

```typescript
async function getPair(): Promise<Pair> {
  const pairAddress = Pair.getAddress(DAI, WETH[DAI.chainId])

  const reserves = [/* use pairAddress to fetch reserves here */]
  const [reserve0, reserve1] = reserves

  const tokens = [DAI, WETH[DAI.chainId]]
  const [token0, token1] = tokens[0].sortsBefore(tokens[1]) ? tokens : [tokens[1], tokens[0]]

  const pair = new Pair(new TokenAmount(token0, reserve0), new TokenAmount(token1, reserve1))
  return pair
}
```
Could you be more specific as to how to fetch the reserves? Is this provided by the Uniswap SDK or do we have to use web3?

**Comment by TeNNoX** [comment]
@i-schuetz What's the solution?

**Comment by i-schuetz** [comment]
@TeNNoX I don't remember well, but I believe that I ended using either ethers.js or web3 to do it.

**Comment by i-schuetz** [comment]
@TeNNoX I don't remember well, but I believe that I ended using either ethers.js or web3 (to call functions in the uniswap smart contract).

**Comment by aress31** [comment]
That's totally retarded tbh, don't get why `Fetcher.fetchPairData` was removed without any easy/pleasant replacement method to use to create a `Pair`. This adds a lot of useless boilerplate code!
