### ISSUE TITLE
getTokenReserves throw an error for DGD

### ISSUE THREAD

**Issue by mqklin** [Uniswap/uniswap-sdk#5]
`getTokenReserves('0xE0B7927c4aF23765Cb51314A0E0521A9645F0E2A')`
throws
```
Uncaught (in promise) 
Error: call exception 
(address="0xE0B7927c4aF23765Cb51314A0E0521A9645F0E2A", method="decimals()", args=[], version=4.0.32) 
at Object.n [as throwError] (ethers.min.js?e7ea:1) 
at eval (ethers.min.js?e7ea:1)
```

**Comment by haydenadams** [comment]
@mqklin yeah that's DGD which doesn't have decimals implemented in properly in their token contract. We manually override this on our frontend but it should be properly handled on the SDK as well.

**Comment by mqklin** [comment]
@haydenadams could you please give me any eta on when will you fix this?

**Comment by NoahZinsmeister** [comment]
I'm a little bit loath to include token-specific overrides in a general-purpose SDK. @mqklin would it be sufficient for `getTokenReserves` to have an option to pass in decimals manually? This would mean you'd have to recognize cases like DGD on your end and pass the override accordingly.

**Comment by mqklin** [comment]
I think yes! But maybe (just an idea) you can do on your end: `if (exchangeAddress === DGD_EXCHANGE_ADDRESS)` - I think it would be better for future users of this SDK

**Comment by mqklin** [comment]
@haydenadams @NoahZinsmeister hey guys, do you support this lib? Seems like `getTokenReserves` is essential API, because we don't need this lib if this is not fixed (we use it to get exchange rate)

**Comment by alexfisher** [comment]
FWIW, DigixDAO has passed a vote to dissolve the DAO near the end of the quarter.  All DGD will be redeemable for a pro-rated share of ETH held by the DAO. DGD will be going away.

**Comment by mqklin** [comment]
Ok, thanks! So I think this can be closed!
