### ISSUE TITLE
Passed bigNumber is negative for some assets

### ISSUE THREAD

**Issue by mrdavey** [Uniswap/uniswap-sdk#6]
Hi there! 👋

I'm using the latest SDK and getting the following error on some assets:

> UnhandledPromiseRejectionWarning: Error: Passed bigNumber '-1.993999755260833107022e+21' is not a valid uint256.
    at ensureUInt256 (/PROJECT_DIR/node_modules/@uniswap/sdk/dist/_utils/index.js:31:15)
    at Array.forEach (<anonymous>)
    at Object.ensureAllUInt256 (/PROJECT_DIR/node_modules/@uniswap/sdk/dist/_utils/index.js:35:16)
    at getOutputPrice (/PROJECT_DIR/node_modules/@uniswap/sdk/dist/computation/trade.js:33:14)
    at getSingleTradeTransput (/PROJECT_DIR/node_modules/@uniswap/sdk/dist/computation/trade.js:44:11)
    at getTradeTransput (/PROJECT_DIR/node_modules/@uniswap/sdk/dist/computation/trade.js:88:29)
    at getTradeDetails (/PROJECT_DIR/node_modules/@uniswap/sdk/dist/computation/trade.js:116:14)

Example code:
```
    let usdc = await getTokenReserves("0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48")
    let marketDetails = getMarketDetails(undefined, usdc)
    let tradeAmount = toWei(2)
    let tradeDetails = getTradeDetails('OUTPUT', tradeAmount, marketDetails)
```

The same also applies when using the WBTC asset (0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599) for `await getTokenReserves()`.

The code works as expected if `OUTPUT` is changed to `INPUT`, or if other assets are used (e.g. DAI - 0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359)

P.S. `toWei()` is a helper that returns the correct bigNumber needed, so I don't think that is the problem.

**Comment by NoahZinsmeister** [comment]
Hmm, are you sure that `toWei()` always returns a bignumber from the [bignumber.js](https://github.com/MikeMcl/bignumber.js/) library? With 18 decimals? Looks like the conversion might be bugged to me.

**Comment by mrdavey** [comment]
Yep I'm certain. I get the same behaviour if I replace the `toWei()` line with: `let tradeAmount = (new BigNumber(amount)).multipliedBy(10 ** 18)`

**Comment by NoahZinsmeister** [comment]
@mrdavey would you mind creating a reproducible example of this bug on codesandbox?

**Comment by NoahZinsmeister** [comment]
Ah @mrdavey i think it's as simple as using `TRADE_EXACT.OUTPUT` instead of `'OUTPUT'`, where `TRADE_EXACT` comes from `import { TRADE_EXACT } from '@uniswap/sdk'`. Let me know if this solves your issue!

**Comment by mrdavey** [comment]
Thanks @NoahZinsmeister . I tried that but unfortunately the error still persists. In your codesandbox, you multiplied by `new BigNumber(2).pow(18)`. Shouldn't this be `new BigNumber(10).pow(18)` instead?

I forked your codesandbox and replicated the bigNumber error I was getting here: https://codesandbox.io/embed/wonderful-hellman-c4h2g

**Comment by mrdavey** [comment]
@NoahZinsmeister any thoughts on how to fix this issue?

**Comment by mrdavey** [comment]
I finally solved this.  The problem is with the 'wei' conversion as WBTC does not use the standard 18 decimal places. E.g. WBTC uses 6 decimal places.
