### ISSUE TITLE
Upgrade to ethers.js v5

### ISSUE THREAD

**Issue by pcowgill** [Uniswap/uniswap-sdk#7]

**Comment by NoahZinsmeister** [comment]
hey @pcowgill, thanks for this. the next version of the sdk will certainly use ethers v5, and will likely also use native [`BigInt`s](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt). this new version will probably only be released with/after the Uniswap v2 launch though, which will likely be sometime early next year.

**Comment by pcowgill** [comment]
@NoahZinsmeister I'm excited that this landed! Thanks!

**Comment by NoahZinsmeister** [comment]
🎉

the next QoL upgrade will be when `BigInt` support lands in react native and safari so we don't have to keep using stupid polyfills
